#!/usr/bin/env python3

from datetime import datetime
from os import path
import re

threshold = 15
log = path.expanduser("~/.unison/unison.log")
now = datetime.now()

with open(log) as f:
    for l in reversed(list(f)):
            if "finished propagating changes" in l:
                res = re.search('UNISON.*at ([0-9:]{8})\.[0-9]{2} on (.*)', l)
                time = res.group(1)
                date = res.group(2)
                last_sync = datetime.strptime(
                    f"{date} {time}",
                    "%d %b %Y %H:%M:%S"
                )
                delta = int((now - last_sync).seconds / 60)
                color = ''
                if delta >= threshold:
                    print((
                        f'last sync {delta} minutes ago\n'
                        f'last sync {delta} minutes ago\n'
                        '#dc322f\n'
                    ))
                break
